-- ============================================================================
--  LE DROIT DE LIRE « projects » AVAIT DISPARU POUR LES CONNECTES (v601)
-- ============================================================================
--  Symptome signale : creer un projet repondait « permission denied for table
--  projects » (42501). L'INSERTION etait pourtant autorisee — c'est le
--  « .select() » qui la suit, pour relire la ligne creee, qui etait refuse.
--
--  CE N'EST PAS UNE REGLE RLS, C'EST UN DROIT SQL. Les deux se confondent
--  facilement parce qu'ils rendent le meme code d'erreur (42501). Le droit SQL
--  dit « as-tu le droit de toucher cette table » ; la regle RLS dit « quelles
--  LIGNES as-tu le droit de voir ». Sans le premier, les secondes ne sont meme
--  pas consultees.
--
--  LA PREUVE QUE C'EST UN ACCIDENT ET PAS UNE DECISION : la table porte TROIS
--  regles de lecture ecrites pour « authenticated » (proprietaire, membre via
--  can_view_project, administrateur). Ecrire trois regles pour un role a qui
--  on aurait retire le droit de lire n'a aucun sens. Et le trou est UNIQUE
--  dans tout le schema : verifie table par table, role par role, c'est le seul
--  endroit ou une regle RLS existe pour un role sans le droit qui va avec.
--  Le role « anon » avait d'ailleurs garde sa lecture.
--
--  RIEN N'EST OUVERT AU PASSAGE : RLS reste active, et ce sont les trois
--  regles ci-dessus qui decident des lignes visibles. Verifie apres coup :
--  38 projets en base, 3 vus par leur proprietaire, 0 par une adresse
--  inconnue. On rend le droit d'entrer dans la piece, pas celui de lire les
--  dossiers des autres.
--
--  LA REQUETE QUI TROUVE CE GENRE DE TROU, a garder :
--    select distinct p.tablename, p.cmd, rn.role_name
--      from pg_policies p
--      cross join lateral unnest(p.roles) as rn(role_name)
--     where p.schemaname = 'public'
--       and rn.role_name in ('anon','authenticated')
--       and not has_table_privilege(rn.role_name,
--             ('public.' || p.tablename)::regclass, p.cmd);
--  Elle doit ne rien renvoyer.
-- ============================================================================

grant select on public.projects to authenticated;
